str=" hello team good morning ";
console.log(str);
console.log(str.length);
console.log(str.toUpperCase());
console.log(str.toLowerCase());
console.log(str.trim());
console.log(str.trimRight());
console.log(str.trimLeft());
console.log(str.substring(3));
console.log(str.replace("team","members"));
console.log(str.split());
console.log(str.split(""));
console.log(str.split(" "));
console.log(str.startsWith(" hello"));
console.log(str.endsWith("morning "));
van=str.split(" ");
console.log(arr);
my=van.join(" ");
console.log(my);